Migrere chevron
navikt/nav-dekoratoren_legacy pull request #1087
Opened 2022-03-04 10:54 UTC by bdahle

2022-03-15 08:53 UTC, bdahle commented
Kanskje vi kan fikse code smells i feature-branchen? Noe duplikat til andre PRs

2022-03-21 16:54 UTC, terjeofnorway requested changes

2022-03-21 16:54 UTC, terjeofnorway commented on package.json
> +        "add": "^2.0.6",
Hvor brukes add-pakken? Finner den ikke i noen av de endrede filene såvidt jeg kan se...

2022-03-21 16:54 UTC, terjeofnorway commented on src/komponenter/header/common/sprakvelger/SprakVelger.less
> +            width: 20px;
Kunne vi satt dette i rems? (1.25rem i dette tilfellet). Vet det ikke alltid er helt konsekvent i eksisterende kode, altså, men det er enheten vi prøver å jobbe i der det er mulig.

2022-03-22 08:02 UTC, bdahle commented on package.json
> +        "add": "^2.0.6",
Veldig godt spørsmål. Fjernet både add og yarn nå, uten at det ser ut til å påvirke noe

2022-03-22 08:02 UTC, bdahle commented on src/komponenter/header/common/sprakvelger/SprakVelger.less
> +            width: 20px;
Jepp!

2022-03-22 13:33 UTC, merged