Desktop dropdown-meny
navikt/nav-dekoratoren_legacy pull request #123
Opened 2020-02-18 15:51 UTC by anders-nom

TODO:
-Fiks for IE11
-Evt. design-endringer

2020-02-19 12:06 UTC, mjansrud commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/DesktopVisningsmeny.less
> -            }
Ref samtale med @anders-nom, se om ms-grid har noen effekt

2020-02-19 12:07 UTC, mjansrud commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/DesktopVisningsmeny.less
> +        //transform-origin: 125px top;
Fjerne denne?

2020-02-19 12:09 UTC, mjansrud commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/keyboard-navigation/kb-navi-graph-builder.ts
> +};
Keyboard navigasjon funker råbra 💯

2020-02-19 12:11 UTC, mjansrud commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/meny-uinnlogget/MenyUinnlogget.less
> +      }
Fjerne ms-grid her også?

2020-02-19 12:13 UTC, mjansrud commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/meny-uinnlogget/MenyUinnlogget.tsx
> +
Use redux-hooks her? :) 
https://react-redux.js.org/next/api/hooks

F.eks
`const language = useSelector(state => state.language)`

2020-02-19 12:16 UTC, mjansrud requested changes
Ser totalt sett veldig bra ut :) 
Har et par endringsforslag, ref kommentarene

2020-02-19 15:00 UTC, anders-nom commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/meny-uinnlogget/MenyUinnlogget.less
> +      }
Fjernet disse ettersom grid ikke brukes her lengre. Testet at flexbox oppsettet fungerer i IE11. ✔️

2020-02-19 15:01 UTC, anders-nom commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/DesktopVisningsmeny.less
> +        //transform-origin: 125px top;
Fjernet. Kan evt justere animasjonen senere sammen med design (men blir neppe akkurat denne :) ).

2020-02-19 15:53 UTC, anders-nom commented
Fikset noen bugs + diverse justeringer

2020-02-20 11:04 UTC, Havardmj commented on src/komponenter/header/meny/Desktopmeny.tsx
> +                        <Ekspanderbarmeny isMobile={false} />
Hvorfor trenger du denne verdien? Har allerede en event.listener inn i Ekspanderbarmeny som definerer om det er desktop eller mobilflate.

2020-02-20 11:04 UTC, Havardmj commented on src/komponenter/header/meny/ekspanderbar-meny/Ekspanderbarmeny.tsx
> +                                        <div className="media-sm-mobil menyvisning-mobil-tablet">
her vil ikke serveren rendre mobil fordi den blir wrappet inn i 'isMobile'. Har allerede :
 div className="media-mobil-tablet menyvisning-mobil-tablet": for mobil og 
    div className="media-lg-desktop menyvisning-desktop": for desktop

2020-02-20 11:04 UTC, Havardmj commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/DesktopVisningsmeny.tsx
> +            <MenyUinnlogget
Hvorfor heter komponenten   <MenyUinnlogget/> ?

2020-02-20 11:04 UTC, Havardmj commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/keyboard-navigation/kb-navi-graph-builder.ts
> +};
bra jobbet med keyboard nav 💯

2020-02-20 15:47 UTC, anders-nom commented on src/komponenter/header/meny/Desktopmeny.tsx
> +                        <Ekspanderbarmeny isMobile={false} />
Jeg la inn dette flagget for å hindre at både MobilVisningsmeny og DesktopVisningsmeny settes inn i både mobil- og desktop branchene for headeren i DOM'en. Er egentlig bare en quick-fix, en mer permanent løsning kunne være å splitte Ekspanderbarmeny til separate mobil- og desktop-komponenter. Det burde nok inn her først som sist, ettersom det er mye overflødig kode i Ekspanderbarmeny nå.

Det konkrete problemet dette skapte var at alle id'er under disse komponentene ble duplisert, noe som riktignok kan løses på andre måter. Synes uansett det så ut som et litt uheldig pattern å branche desktop/mobil på nytt her, ettersom dette allerede gjøres i Header komponenten.

2020-02-20 15:55 UTC, anders-nom commented on src/komponenter/header/meny/ekspanderbar-meny/Ekspanderbarmeny.tsx
> +                                        <div className="media-sm-mobil menyvisning-mobil-tablet">
Se over. Så vidt jeg forstår vil både mobil og desktop renderes der de er relevante, ettersom Ekspanderbarmeny også ligger i Mobilmeny komponenten, der dette flagget er true.

2020-02-20 16:01 UTC, anders-nom commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/DesktopVisningsmeny.tsx
> +            <MenyUinnlogget
Dette er vel menyen for uinnlogget innhold. Det var litt frem og tilbake med design hvor de forskjellige knappene skulle ligge på menylinjen, så hvis denne endte opp på høyre side ville det bli litt merkelig. :)
Nå forble jo denne til venstre, så tja...

2020-02-21 09:27 UTC, Havardmj commented on src/komponenter/header/meny/Desktopmeny.tsx
> +                        <Ekspanderbarmeny isMobile={false} />
ingen id som ligger under dem som var duplisert, eller trenger å være det. Ved å sette css som kontroller over view, så får serveren rendret alt innholdet slik strukturen er. Ved å sette js boolean som wrapper rundt halvparten så blir ikke dette rendret på server, noe som er uheldig.

2020-02-21 09:29 UTC, Havardmj commented on src/komponenter/header/meny/Desktopmeny.tsx
> +                        <Ekspanderbarmeny isMobile={false} />
Om man splitter ekspanderbarmeny eller holder den som et bindeledd gjør egentlig ikke noe forskjell/effekt. Det går på hva en prefererer.

2020-02-21 10:56 UTC, anders-nom commented on src/komponenter/header/meny/Desktopmeny.tsx
> +                        <Ekspanderbarmeny isMobile={false} />
Hmm, dette hadde vært enklere å forklare med litt tegning. :)

Problemet er at det allerede finnes separate desktop/mobil branches i Header komponenten (der CSS styrer hvilken som vises). Hver av disse branchene får sin egen instans av Ekspanderbarmeny, som igjen har hver sin instans av både DesktopVisningsmeny og MobilVisningsmeny. Dermed finnes det alltid to kopier av alt under disse i DOM'en, selv om mobil-viewet aldri viser desktop-menyen og omvendt.

Når jeg tenker meg om så er dette kanskje gjort for at smal desktop/tablet skulle kunne få mobil-menyen, men disse får nå isteden en smalere versjon av desktop-meny. Tror uansett jeg bør refaktorere et par ting her for å tilpasse endringene som er gjort, så jeg lukker denne inntil det er gjort.

2020-02-25 09:12 UTC, Havardmj commented on src/komponenter/header/meny/ekspanderbar-meny/desktop-visningsmeny/DesktopVisningsmeny.tsx
> +            <MenyUinnlogget
Var opprinnelig venstre og høyredel. Så fjernet vi høyre uten å rename den som var igjen. Mao hadde feil navn.

2020-02-25 09:16 UTC, Havardmj commented on src/komponenter/header/meny/ekspanderende-menyer/meny-uinnlogget-desktop/meny-dropdown/UinnloggetDropdown.tsx
> +export const UinnloggetDropdown = (props: Props) => {
Igjen hvorfor UinnloggetDropdown ???!
UinnloggetDropdown impliserer at det finnes komponent som heter <InnloggetDropdown />

2020-02-25 09:16 UTC, Havardmj commented on src/komponenter/header/meny/ekspanderende-menyer/meny-uinnlogget-desktop/meny-dropdown/UinnloggetDropdown.tsx
> +export const UinnloggetDropdown = (props: Props) => {
Kan den ikke bare heter Dropdown, eller DropdownContent, eller DesktopDropdown ?

2020-02-25 13:04 UTC, mjansrud approved these changes

2020-02-25 13:11 UTC, merged