Expose initial amplitude user properties
navikt/nav-dekoratoren_legacy pull request #1452
Opened 2023-06-20 13:42 UTC by max-nav

## Oppsummering av hva som er gjort

Eks:

-   Forslag til å sette user properties

2023-07-03 11:30 UTC, terjeofnorway requested changes

2023-07-03 11:30 UTC, terjeofnorway commented on src/server/utils.ts
> +                INITIAL_USER_PROPS: parseUriObject(req.query.initialUserProps as string),
Får ikke lagt inn kommentar på urørte kodelinjer, så denne refererer til validateClientEnv i linje 90:
Burde vi også legge inn validering av initialUserProps?

2023-07-03 11:30 UTC, terjeofnorway commented on src/utils/analytics/amplitude.ts
> +export const initAmplitude = (initialUserProps?: object) => {
Skulle vi definert type for initialUserProps fremfor kun `object`?

2023-07-03 11:30 UTC, terjeofnorway commented on src/server/utils.ts
> +                INITIAL_USER_PROPS: parseUriObject(req.query.initialUserProps as string),
...og kunne et alternativ være å kalle dette initialAnalyticsConfig istedet? Så blir det helt spesifikt i kode hva dette er ment å brukes til.

2023-07-03 11:30 UTC, terjeofnorway commented on src/utils/analytics/analytics.ts
> +    initialUserProps?: object;
Samme som ovenfor - foreslår mer spesifikk type fremfor `object`.

2023-07-04 12:08 UTC, terjeofnorway commented on src/utils/analytics/amplitude.ts
> +export const initAmplitude = (initialUserProps?: object) => {
Sorry, jeg som misforstod. Nevermind!

2023-07-04 12:20 UTC, max-nav commented
- [ ] Skrive inn i readme under amplitude-klient
- [ ] Få det inn i dekoratøren moduler

2023-07-07 09:23 UTC, anders-nom approved these changes

2024-03-05 09:33 UTC, closed without merging