Adds filter change to the chatbot
navikt/nav-dekoratoren_legacy pull request #1494
Opened 2023-09-28 06:21 UTC by mamikals

## Oppsummering av hva som er gjort

Eks:

-   Endrer type i foobar-objektet.
-   Oppdaterer diverse destruct etter typeendringer.

## Testing

Eks: Har testet selv i dev / q6

## Dette trenger jeg å få et ekstra blikk på

Eks: Sjekk om du er enig i hvordan objektet destructes med default-verdi.

## Skjermbilde hvis relevant

2023-09-29 07:31 UTC, terjeofnorway requested changes
Hadde én kommentar bare. Dessuten, kan du oppdatere beskrivelsen i PR'en? Den teksten som er der nå er bare eksempel-tekst :)

2023-09-29 07:31 UTC, terjeofnorway commented on src/csp.ts
> +const googleStorage = 'https://storage.googleapis.com';
Det skal holde å oppgi host uten protokollen, så du kan fjerne `https://` tror jeg.

2023-09-29 07:36 UTC, mamikals commented on src/csp.ts
> +const googleStorage = 'https://storage.googleapis.com';
Det stemmer nok, jeg kan fjerne den 😄

2023-09-29 07:55 UTC, mamikals commented
Det kan jeg godt 😄, jeg la merke til noen ekstra problemer siden jeg skulle oppdatere beskrivelsen. Så jeg kommer til å ta bort noen av endringene, for så å diskutere det med teamet om de ønsker å ha det slikt.
Men resten av endringene kan godt merges inn, de er ønskelige fortsatt.

2023-10-02 10:45 UTC, terjeofnorway approved these changes

2023-10-02 10:45 UTC, merged