Include domain settings on removeCookie
navikt/nav-dekoratoren_legacy pull request #1535
Opened 2024-04-08 05:53 UTC by mamikals

## Oppsummering av hva som er gjort

Eks:
Det er problemer med chatboten og cookies, removeCookie metoden som er inkludert i react-cookie sletter faktisk ikke cookien. Jeg mistenker at det er pga. domains i cookiene, så jeg tenker å prøve med det satt.

## Testing
Har testet det lokalt, men der klarte jeg heller ikke å gjenskape det originale problemet heller.

## Dette trenger jeg å få et ekstra blikk på
Det hadde vært fint hvis jeg kunne teste det i dev.nav.no først, men siden dere holder på med den nye dekoratøren forstår jeg det hvis dere ikke vil det.

## Skjermbilde hvis relevant

2024-04-10 10:33 UTC, terjeofnorway requested changes

2024-04-10 10:33 UTC, terjeofnorway commented on src/komponenter/footer/chatbot/ChatbotWrapper.tsx
> +    const isDevelopment: boolean = process.env.NODE_ENV === 'development';
Kunne vi heller navnet denne isLocal og sjekket på `env === 'localhost'`?

2024-04-10 10:37 UTC, mamikals commented on src/komponenter/footer/chatbot/ChatbotWrapper.tsx
> +    const isDevelopment: boolean = process.env.NODE_ENV === 'development';
Det kan vi godt 😄, jeg tok bare utgangspunktet i det som var gjort i CookieSettings filen.

2024-04-17 09:10 UTC, terjeofnorway approved these changes

2024-04-17 09:10 UTC, merged